library(shinytest2)

# Increase timeout time
options(shinytest2.timeout = 40000)  # 40 seconds
# Increase wait time before screenshot comparisons
options(shinytest2.wait_for_idle = 2000)


test_that("{shinytest2} recording: www_elements", {
  app <- AppDriver$new(variant = platform_variant(), name = "www_elements", seed = 8,
                       height = 585, width = 979)
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "appfeatures")
  app$set_inputs(tabs_after_analysis = "appfeatures")
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "report")
  app$set_inputs(tabs_after_analysis = "report")
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  app$expect_screenshot()
  app$click("data_upload-demo_help")
  app$expect_screenshot()
  app$click("data_upload-omics_data_help")
  app$expect_screenshot()
})

test_that("{shinytest2} recording: data_upload_hf", {
  app <- AppDriver$new(variant = platform_variant(), name = "data_upload_hf", seed = 1,
      height = 585, width = 979)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = c("testdata/holter.csv", "testdata/mrna.csv"))
  app$set_inputs(`data_upload-response_var` = "Sex")
  app$expect_screenshot()
  app$set_inputs(`data_upload-response_var` = "NYHA_class")
  app$set_inputs(`data_upload-ref_var` = "1")
  app$expect_screenshot()
  app$click("data_upload-run")
  app$expect_screenshot()
})

test_that("{shinytest2} recording: metadata_hf", {
  app <- AppDriver$new(variant = platform_variant(), name = "metadata_hf", seed = 2,
      height = 585, width = 979)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo.csv")
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = c("testdata/holter.csv", "testdata/mrna.csv"))
  app$set_inputs(`data_upload-response_var` = "Sex")
  app$click("data_upload-run")
  app$set_inputs(sidebarItemExpanded = "Analysis")
  app$set_inputs(tabs_before_analysis = "subitem1")
  app$set_inputs(tabs_after_analysis = "subitem1")
  app$expect_screenshot()
  app$wait_for_js("document.querySelector('#metadata-lr') !== null") # wait for metadata-lr to appear
  app$click("metadata-lr")
  app$expect_screenshot()
  app$set_inputs(`metadata-test` = "ks")
  app$expect_screenshot()
  app$set_inputs(`metadata-transform` = "yes")
  app$expect_screenshot()
  app$set_inputs(`metadata-cont_var` = "Heart_Rate")
  app$expect_screenshot()
  app$expect_screenshot()
  app$set_inputs(`metadata-cat_var` = "Diabetes_Mellitus")
  app$expect_screenshot()
  app$expect_screenshot()
})

test_that("{shinytest2} recording: eda_hf", {
  app <- AppDriver$new(variant = platform_variant(), name = "eda_hf", seed = 3, height = 585,
      width = 979)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = c("testdata/holter.csv", "testdata/mrna.csv"))
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo.csv")
  app$set_inputs(`data_upload-response_var` = "Sex")
  app$click("data_upload-run")
  app$set_inputs(sidebarItemExpanded = "Analysis")
  app$set_inputs(tabs_before_analysis = "subitem2")
  app$set_inputs(tabs_after_analysis = "subitem2")
  app$set_inputs(`edaholter_-ncomp` = 2)
  app$set_inputs(`edamrna_-ncomp` = 2)
  app$set_inputs(`edaholter_-pval` = "pvalue")
  app$set_inputs(`edamrna_-pval` = "pvalue")
  app$expect_screenshot()
  app$set_inputs(`edaholter_-pval` = "fdr")
  app$expect_screenshot()
  app$set_inputs(`edaholter_-ncomp` = 3)
  app$expect_screenshot()
  app$expect_screenshot()
})

test_that("{shinytest2} recording: dea_hf", {
  app <- AppDriver$new(variant = platform_variant(), name = "dea_hf", seed = 4, height = 585,
      width = 979)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo.csv")
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = c("testdata/holter.csv", "testdata/mrna.csv"))
  app$set_inputs(`data_upload-response_var` = "Sex")
  app$click("data_upload-run")
  app$set_inputs(sidebarItemExpanded = "Analysis")
  app$set_inputs(tabs_before_analysis = "subitem3")
  app$set_inputs(tabs_after_analysis = "subitem3")
  app$set_inputs(`deaholter_-variable_name` = "")
  app$set_inputs(`deamrna_-variable_name` = "")
  app$click("deaholter_-search_button")
  app$click("deaholter_-dePlotOps_button")
  app$click("deaholter_-plot_help")
  app$click("deaholter_-button")
  app$click("deaholter_-pathwayEnrichmentOps_button")
  app$click("deamrna_-search_button")
  app$click("deamrna_-dePlotOps_button")
  app$click("deamrna_-plot_help")
  app$click("deamrna_-button")
  app$click("deamrna_-pathwayEnrichmentOps_button")
  app$set_inputs(`deaholter_-fdr` = 0.15)
  app$set_inputs(`deaholter_-enrichmentSlider` = 5)
  app$set_inputs(`deaholter_-drugEnrichmentUpSlider` = 5)
  app$set_inputs(`deaholter_-drugEnrichmentDownSlider` = 5)
  app$set_inputs(`deamrna_-fdr` = 0.15)
  app$set_inputs(`deamrna_-enrichmentSlider` = 5)
  app$set_inputs(`deamrna_-drugEnrichmentUpSlider` = 5)
  app$set_inputs(`deamrna_-drugEnrichmentDownSlider` = 5)
  app$set_inputs(`deaholter_-comparison` = "M vs. F")
  app$set_inputs(`deaholter_-deTest` = "limma")
  app$set_inputs(`deamrna_-comparison` = "M vs. F")
  app$set_inputs(`deamrna_-deTest` = "limma")
  app$expect_screenshot()
  app$expect_screenshot()
  app$expect_screenshot()
  app$set_inputs(`deaholter_-variable_name` = "HR_MIN")
  app$click("deaholter_-dePlotOps_button")
  app$set_inputs(`deaholter_-dePlotOps_hjust` = 0.5)
  app$set_inputs(`deaholter_-dePlotOps_vjust` = 0.5)
  app$set_inputs(`deaholter_-dePlotOps_xAngle` = 0)
  app$set_inputs(`deaholter_-dePlotOps_xSize` = 7)
  app$set_inputs(`deaholter_-dePlotOps_ySize` = 7)
  app$expect_screenshot()
  app$click("deaholter_-plot_help")
  app$expect_screenshot()
  app$set_inputs(`deaholter_-deTest` = "ols")
  app$expect_screenshot()
  app$set_inputs(`deaholter_-fdr` = 0.115)
  app$expect_screenshot()
  app$click("deaholter_-button")
  app$expect_screenshot()
  app$set_inputs(`deaholter_-deTest` = "ols")
  app$expect_screenshot()
  app$expect_screenshot()
  app$expect_screenshot()
})

test_that("{shinytest2} recording: biomarkerPanels_hf", {
  app <- AppDriver$new(variant = platform_variant(), name = "biomarkerPanels_hf",
      seed = 5, height = 585, width = 979)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = c("testdata/holter.csv", "testdata/mrna.csv"))
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo.csv")
  app$set_inputs(`data_upload-response_var` = "Sex")
  app$click("data_upload-run")
  app$set_inputs(sidebarItemExpanded = "Analysis")
  app$set_inputs(tabs_before_analysis = "subitem4")
  app$set_inputs(tabs_after_analysis = "subitem4")
  app$wait_for_js("document.querySelector('#biomarker_discovery_analysis-build') !== null") # wait for biomarker_discovery_analysis-build to appear
  app$click("biomarker_discovery_analysis-build")
  app$click("biomarker_discovery_analysis-biomarker_plot-variable_options_button")
  app$set_inputs(`biomarker_discovery_analysis-alpha` = c(0.7, 1))
  app$set_inputs(`biomarker_discovery_analysis-corCutoff` = 0.5)
  app$set_inputs(`biomarker_discovery_analysis-bioFDR` = 0.05)
  app$set_inputs(`biomarker_discovery_analysis-cvScheme` = "fiveFold")
  app$set_inputs(`biomarker_discovery_analysis-pcaBasePanelRadioButtons` = " ")
  app$set_inputs(`biomarker_discovery_analysis-heatmapBasePanelRadioButtons` = " ")
  app$set_inputs(`biomarker_discovery_analysis-selectedGroups` = c("M", "F"))
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_single` = character(0))
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_ensemble` = character(0))
  app$set_inputs(`biomarker_discovery_analysis-seed` = 42)
  app$set_inputs(`biomarker_discovery_analysis-alphaGrid` = 5)
  app$set_inputs(`biomarker_discovery_analysis-n_repeats` = 5)
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_single` = "holter")
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_single` = character(0))
  app$expect_screenshot()
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_single` = "holter")
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_ensemble` = "holter")
  app$click("biomarker_discovery_analysis-build")
  app$expect_screenshot()
  app$expect_screenshot()
  app$click("biomarker_discovery_analysis-biomarker_plot-variable_options_button")
  app$click("biomarker_discovery_analysis-biomarker_plot-variable_options_button")
  app$wait_for_js("document.querySelector('#biomarker_discovery_analysis-biomarker_panels-dotplot_options_button') !== null") # wait for button to appear
  app$click("biomarker_discovery_analysis-biomarker_panels-dotplot_options_button")
  app$set_inputs(`biomarker_discovery_analysis-biomarker_panels-hjust` = 0.5)
  app$set_inputs(`biomarker_discovery_analysis-biomarker_panels-vjust` = 0.5)
  app$set_inputs(`biomarker_discovery_analysis-biomarker_panels-xAngle` = 0)
  app$set_inputs(`biomarker_discovery_analysis-biomarker_panels-xSize` = 7)
  app$set_inputs(`biomarker_discovery_analysis-biomarker_panels-ySize` = 7)
  app$expect_screenshot()
  app$expect_screenshot()
  app$expect_screenshot()
  app$expect_screenshot()
  app$set_inputs(`biomarker_discovery_analysis-corCutoff` = 0.555)
  app$set_inputs(`biomarker_discovery_analysis-bioFDR` = 0.15)
  app$set_inputs(`biomarker_discovery_analysis-bioFDR` = 0.08)
  app$expect_screenshot()
})

test_that("{shinytest2} recording: upload_error_msgs_hf", {
  app <- AppDriver$new(variant = platform_variant(), name = "upload_error_msgs_hf",
      seed = 6, height = 585, width = 979)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter.csv")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo_no_categoricals.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo_no_header.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo.csv")
  app$set_inputs(`data_upload-response_var` = "Sex")
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter_less_rows.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter_no_header.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter_NA_value.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter_empty_entry.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter_empty_column.csv")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter.csv")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/texttestfile.txt")
  app$expect_screenshot()
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo.csv")
  app$expect_screenshot()
})

test_that("{shinytest2} recording: NA_LowLeveln_SingleVal_handling_hf", {
  app <- AppDriver$new(variant = platform_variant(), name = "NA_LowLeveln_SingleVal_handling_hf",
      seed = 7, height = 585, width = 979)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-omics_data`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-omics_data` = "testdata/holter.csv")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo_NA_sex.csv")
  app$set_inputs(`data_upload-response_var` = "Sex")
  app$expect_screenshot()
  app$click("data_upload-run")
  app$set_inputs(sidebarItemExpanded = "Analysis")
  app$set_inputs(tabs_before_analysis = "subitem1")
  app$set_inputs(tabs_after_analysis = "subitem1")
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "subitem2")
  app$set_inputs(tabs_after_analysis = "subitem2")
  app$set_inputs(`edaholter_-ncomp` = 2)
  app$set_inputs(`edaholter_-pval` = "pvalue")
  app$set_inputs(tabs_before_analysis = "subitem3")
  app$set_inputs(tabs_after_analysis = "subitem3")
  app$set_inputs(`deaholter_-variable_name` = "")
  app$click("deaholter_-search_button")
  app$click("deaholter_-dePlotOps_button")
  app$click("deaholter_-plot_help")
  app$click("deaholter_-button")
  app$click("deaholter_-pathwayEnrichmentOps_button")
  app$set_inputs(`deaholter_-fdr` = 0.15)
  app$set_inputs(`deaholter_-enrichmentSlider` = 5)
  app$set_inputs(`deaholter_-drugEnrichmentUpSlider` = 5)
  app$set_inputs(`deaholter_-drugEnrichmentDownSlider` = 5)
  app$set_inputs(`deaholter_-comparison` = "M vs. F")
  app$set_inputs(`deaholter_-deTest` = "limma")
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo_single_value_age.csv")
  app$expect_screenshot()
  app$click("data_upload-run")
  app$set_inputs(tabs_before_analysis = "subitem1")
  app$set_inputs(tabs_after_analysis = "subitem1")
  app$expect_screenshot()
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "subitem2")
  app$set_inputs(tabs_after_analysis = "subitem2")
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo_only_YesNA_hospital.csv")
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "subitem1")
  app$set_inputs(tabs_after_analysis = "subitem1")
  app$set_inputs(`metadata-cat_var` = "hospitalizations")
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  app$click("data_upload-run")
  app$set_inputs(tabs_before_analysis = "subitem1")
  app$set_inputs(tabs_after_analysis = "subitem1")
  app$expect_screenshot()
  app$expect_screenshot()
  app$set_inputs(`metadata-cat_var` = "hospitalizations")
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "subitem2")
  app$set_inputs(tabs_after_analysis = "subitem2")
  app$set_inputs(tabs_before_analysis = "subitem3")
  app$set_inputs(tabs_after_analysis = "subitem3")
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
  rlang::warn(paste0("``data_upload-demo`` should be the path to the file, relative to the app's tests/testthat directory.\n",
      "Remove this warning when the file is in the correct location."))
  app$upload_file(`data_upload-demo` = "testdata/demo_lessthan3_per_level.csv")
  app$set_inputs(`data_upload-response_var` = "NYHA_class")
  app$expect_screenshot()
  app$click("data_upload-run")
  app$expect_screenshot()
  app$set_inputs(`data_upload-ref_var` = "3")
  app$expect_screenshot()
  app$set_inputs(`data_upload-response_var` = "Sex")
  app$expect_screenshot()
  app$click("data_upload-run")
  app$set_inputs(tabs_before_analysis = "subitem1")
  app$set_inputs(tabs_after_analysis = "subitem1")
  app$set_inputs(`metadata-cat_var` = "NYHA_class")
  app$expect_screenshot()
  app$set_inputs(tabs_before_analysis = "subitem2")
  app$set_inputs(tabs_after_analysis = "subitem2")
  app$set_inputs(tabs_before_analysis = "subitem3")
  app$set_inputs(tabs_after_analysis = "subitem3")
  app$set_inputs(tabs_before_analysis = "subitem4")
  app$set_inputs(tabs_after_analysis = "subitem4")
  app$click("biomarker_discovery_analysis-build")
  app$click("biomarker_discovery_analysis-biomarker_plot-variable_options_button")
  app$set_inputs(`biomarker_discovery_analysis-alpha` = c(0.7, 1))
  app$set_inputs(`biomarker_discovery_analysis-corCutoff` = 0.5)
  app$set_inputs(`biomarker_discovery_analysis-bioFDR` = 0.05)
  app$set_inputs(`biomarker_discovery_analysis-cvScheme` = "fiveFold")
  app$set_inputs(`biomarker_discovery_analysis-pcaBasePanelRadioButtons` = " ")
  app$set_inputs(`biomarker_discovery_analysis-heatmapBasePanelRadioButtons` = " ")
  app$set_inputs(`biomarker_discovery_analysis-selectedGroups` = c("M", "F"))
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_single` = character(0))
  app$set_inputs(`biomarker_discovery_analysis-checkGroup_ensemble` = character(0))
  app$set_inputs(`biomarker_discovery_analysis-seed` = 42)
  app$set_inputs(`biomarker_discovery_analysis-alphaGrid` = 5)
  app$set_inputs(`biomarker_discovery_analysis-n_repeats` = 5)
  app$set_inputs(tabs_before_analysis = "data")
  app$set_inputs(tabs_after_analysis = "data")
})

